<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrganizationLocalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('mp_organization_local')->delete();

        \DB::table('mp_organization_local')->insert(
            array(
                0 => array('code' => 'H2 3940', 'description' => 'Abastecimiento HFB', 'organization_id' => '1'),
                1 => array('code' => 'H2 3912', 'description' => 'Admision Ambulatoria HFB', 'organization_id' => '1'),
                2 => array('code' => 'H2 3912 H', 'description' => 'Admision Hospitalizado HFB', 'organization_id' => '1'),
                3 => array('code' => 'H2-M478', 'description' => 'Adolescencia Hfb', 'organization_id' => '1'),
                4 => array('code' => '10-110120-ALIM', 'description' => 'Alimentación HFBC', 'organization_id' => '1'),
                5 => array('code' => 'H2-M269', 'description' => 'Anatomía Patológica Hfb', 'organization_id' => '1'),
                6 => array('code' => 'H2 3913', 'description' => 'Archivo HFB', 'organization_id' => '1'),
                7 => array('code' => 'H2 3913 P', 'description' => 'Archivo Pasivo HFB', 'organization_id' => '1'),
                8 => array('code' => 'H2 AUD', 'description' => 'Auditoría HFB', 'organization_id' => '1'),
                9 => array('code' => '10-110120-UMT', 'description' => 'Banco de Sangre HFBC', 'organization_id' => '1'),
                10 => array('code' => '10-110120-BODEGADEINSUMOSHFBC', 'description' => 'Bodega de Insumos HFBC', 'organization_id' => '1'),
                11 => array('code' => '10-110120-BP', 'description' => 'Botiquin Qx HFBC', 'organization_id' => '1'),
                12 => array('code' => '10-110120-BIUA', 'description' => 'Botiquín de insumos UA HFBC', 'organization_id' => '1'),
                13 => array('code' => '10-110120-BUGO', 'description' => 'Botiquín de Urgencia GO HFBC', 'organization_id' => '1'),
                14 => array('code' => '10-110120-BU', 'description' => 'Botiquín de Urgencia HFBC', 'organization_id' => '1'),
                15 => array('code' => '10-110120-BUI', 'description' => 'Botiquín de Urgencia Infantil HFBC', 'organization_id' => '1'),
                16 => array('code' => 'H2 BCPA', 'description' => 'Broncoscopia HFB', 'organization_id' => '1'),
                17 => array('code' => 'H2 POLI10', 'description' => 'CAE - BRONCO INFANTIL HFB', 'organization_id' => '1'),
                18 => array('code' => 'H2 POLI13', 'description' => 'CAE - CARDIOLOGIA INFANTIL HFB', 'organization_id' => '1'),
                19 => array('code' => 'H2 POLI05', 'description' => 'CAE - CIRUGIA ADULTO AMBULATORIO HFB', 'organization_id' => '1'),
                20 => array('code' => 'H2 POLI19', 'description' => 'CAE - CIRUGIA INFANTIL AMBULATORIO HFB', 'organization_id' => '1'),
                21 => array('code' => 'H2 POLI09', 'description' => 'CAE - CUIDADOS PALIATIVOS HFB', 'organization_id' => '1'),
                22 => array('code' => 'H2 POLI15', 'description' => 'CAE - DERMATOLOGIA HFB', 'organization_id' => '1'),
                23 => array('code' => 'H2 POLI11', 'description' => 'CAE - DIABETES HFB', 'organization_id' => '1'),
                24 => array('code' => 'H2 POLI12', 'description' => 'CAE - ELECTROENCEFALOGRAFIA HFB', 'organization_id' => '1'),
                25 => array('code' => 'H2 POLI20', 'description' => 'CAE - ENDOSCOPIAS HFB', 'organization_id' => '1'),
                26 => array('code' => 'H2 POLI01', 'description' => 'CAE - FAR AMBULATORIO HFB', 'organization_id' => '1'),
                27 => array('code' => 'H2 POLI08', 'description' => 'CAE - GINECOLOGIA AMBULATORIO HFB', 'organization_id' => '1'),
                28 => array('code' => 'H2 POLI14', 'description' => 'CAE - KINESIOLOGIA HFB', 'organization_id' => '1'),
                29 => array('code' => 'H2 POLI06', 'description' => 'CAE - MEDICINA AMBULATORIO HFB', 'organization_id' => '1'),
                30 => array('code' => 'H2 POLI16', 'description' => 'CAE - NEUROLOGIA ADULTO HFB', 'organization_id' => '1'),
                31 => array('code' => 'H2 POLI02', 'description' => 'CAE - PATOLOGIA CERVICAL AMBULATORIO HFB', 'organization_id' => '1'),
                32 => array('code' => 'H2 POLI07', 'description' => 'CAE - PATOLOGIA DE MAMAS AMBULATORIO HFB', 'organization_id' => '1'),
                33 => array('code' => 'H2 POLI03', 'description' => 'CAE - PEDIATRIA AMBULATORIA HFB', 'organization_id' => '1'),
                34 => array('code' => 'H2 POLI21', 'description' => 'CAE - PROCEDIMIENTOS CARDIOLOGIA HFB', 'organization_id' => '1'),
                35 => array('code' => 'H2 POLI18', 'description' => 'CAE - PSIQUIATRIA ADULTO AMBULATORIO HFB', 'organization_id' => '1'),
                36 => array('code' => 'H2 POLI17', 'description' => 'CAE - PSIQUIATRIA INFANTIL HFB', 'organization_id' => '1'),
                37 => array('code' => 'H2-M422', 'description' => 'Cardiologia Adulto Hfb', 'organization_id' => '1'),
                38 => array('code' => 'H2-M441', 'description' => 'Cardiologia Pediatrica Hfb', 'organization_id' => '1'),
                39 => array('code' => 'H2-M388', 'description' => 'Cirugia Cardiovascular Hfb', 'organization_id' => '1'),
                40 => array('code' => 'H2-M387', 'description' => 'Cirugia Coloproctologica Hfb', 'organization_id' => '1'),
                41 => array('code' => 'H2-M383', 'description' => 'Cirugia De Cabeza, Cuello Y Maxilofacial Hfb', 'organization_id' => '1'),
                42 => array('code' => 'H2-M380.1', 'description' => 'Cirugia de Mamas HFB', 'organization_id' => '1'),
                43 => array('code' => 'H2-M385', 'description' => 'Cirugia De Torax Hfb', 'organization_id' => '1'),
                44 => array('code' => 'H2-M382', 'description' => 'Cirugia Digestiva Hfb', 'organization_id' => '1'),
                45 => array('code' => 'H2-M382.1', 'description' => 'Cirugia Digestiva Infantil HFB', 'organization_id' => '1'),
                46 => array('code' => 'H2-M486', 'description' => 'Cirugia Oncologica Cabeza Y Cuello Hfb', 'organization_id' => '1'),
                47 => array('code' => 'H2-M380', 'description' => 'Cirugia Oncologica Hfb', 'organization_id' => '1'),
                48 => array('code' => 'H2-M401', 'description' => 'Cirugia Pediátrica Hfb', 'organization_id' => '1'),
                49 => array('code' => 'H2-M384.1', 'description' => 'Cirugia Plastica Infantil HFB', 'organization_id' => '1'),
                50 => array('code' => 'H2-M384', 'description' => 'Cirugia Plastica Y Reparadora Hfb', 'organization_id' => '1'),
                51 => array('code' => 'H2-M386', 'description' => 'Cirugia Vascular Periferica Hfb', 'organization_id' => '1'),
                52 => array('code' => 'H2-D341', 'description' => 'Cirugia Y Traumatologia Bucomáxilo-facial Hfb', 'organization_id' => '1'),
                53 => array('code' => 'H2- M382.2', 'description' => 'Cirugía Bariátrica HFB', 'organization_id' => '1'),
                54 => array('code' => 'H2-M200', 'description' => 'Cirugía General Hfb', 'organization_id' => '1'),
                55 => array('code' => '10-110120-CMA', 'description' => 'Cirugía Mayor Ambulatoria', 'organization_id' => '1'),
                56 => array('code' => 'H2 3930', 'description' => 'Contabilidad y PPTO. HFB', 'organization_id' => '1'),
                57 => array('code' => 'H2-D276', 'description' => 'Dentista Becario Primario Hfb', 'organization_id' => '1'),
                58 => array('code' => 'H2-D275', 'description' => 'Dentista En Comision De Estudios (Becario De Retorno) Hfb', 'organization_id' => '1'),
                59 => array('code' => 'H2-D274', 'description' => 'Dentista General Etapa Despinacion Y Formacion Hfb', 'organization_id' => '1'),
                60 => array('code' => 'H2-D277', 'description' => 'Dentista Periodo Asistencial Obligatorio Hfb', 'organization_id' => '1'),
                61 => array('code' => 'HD-DPG', 'description' => 'Departamento de Planificación y Control', 'organization_id' => '1'),
                62 => array('code' => 'H2 AUGE', 'description' => 'Departamento GES HFB', 'organization_id' => '1'),
                63 => array('code' => 'H2-GRD', 'description' => 'Departamento GRD HFBC', 'organization_id' => '1'),
                64 => array('code' => 'H2 1920', 'description' => 'Depto. Recursos Humanos HFB', 'organization_id' => '1'),
                65 => array('code' => 'H2-M206', 'description' => 'Dermatología HFB', 'organization_id' => '1'),
                66 => array('code' => 'H2-M435', 'description' => 'Diabetologia Hfb', 'organization_id' => '1'),
                67 => array('code' => 'H2 3100', 'description' => 'Dirección Hospital HFB', 'organization_id' => '1'),
                68 => array('code' => 'H2 ECDG', 'description' => 'Ecocardiograma HFB', 'organization_id' => '1'),
                69 => array('code' => 'H2 ELCD', 'description' => 'Electrocardiograma HFB', 'organization_id' => '1'),
                70 => array('code' => 'H2 EEG', 'description' => 'Electroencefalograma HFB', 'organization_id' => '1'),
                71 => array('code' => 'H2-M442', 'description' => 'Endocrinologia Pediatrica Hfb', 'organization_id' => '1'),
                72 => array('code' => 'H2-D347', 'description' => 'Endodoncia Hfb', 'organization_id' => '1'),
                73 => array('code' => 'H2 ENDO', 'description' => 'Endoscopias HFB', 'organization_id' => '1'),
                74 => array('code' => 'H2-M436', 'description' => 'Enfermedades Respiratorias Adulto Hfb', 'organization_id' => '1'),
                75 => array('code' => 'H2-M492', 'description' => 'Enfermedades Respiratorias Pediatrica Hfb', 'organization_id' => '1'),
                76 => array('code' => 'H2 3204', 'description' => 'Estadistica HFB', 'organization_id' => '1'),
                77 => array('code' => 'H2 3970', 'description' => 'Esterilización HFB', 'organization_id' => '1'),
                78 => array('code' => '10-110120-FA', 'description' => 'Farmacia Ambulatoria HFBC', 'organization_id' => '1'),
                79 => array('code' => '10-110120-FH', 'description' => 'Farmacia Hospitalizados HFBC', 'organization_id' => '1'),
                80 => array('code' => 'H2 3961.1', 'description' => 'Farmacia Restringidos HFB', 'organization_id' => '1'),
                81 => array('code' => '10-110120-FIS', 'description' => 'Fisiatria HFB', 'organization_id' => '1'),
                82 => array('code' => 'H2 3990', 'description' => 'Fonoaudiologia', 'organization_id' => '1'),
                83 => array('code' => 'H2-M426', 'description' => 'Gastroenterologia Adulto Hfb', 'organization_id' => '1'),
                84 => array('code' => 'H2-M443', 'description' => 'Gastroenterologia Pediatrica Hfb', 'organization_id' => '1'),
                85 => array('code' => 'H2-M494', 'description' => 'Genetica Clinica Hfb', 'organization_id' => '1'),
                86 => array('code' => 'H2-M427', 'description' => 'Geriatria Hfb', 'organization_id' => '1'),
                87 => array('code' => 'H2 4004', 'description' => 'Gestión y Calidad HFB', 'organization_id' => '1'),
                88 => array('code' => 'H2-M481', 'description' => 'Ginecologia Oncológica Hfb', 'organization_id' => '1'),
                89 => array('code' => 'H2-M479', 'description' => 'Ginecologia Pediatrica Y Adolescencia Hfb', 'organization_id' => '1'),
                90 => array('code' => 'H2 4442', 'description' => 'GRD HFBC', 'organization_id' => '1'),
                91 => array('code' => 'H2-M428', 'description' => 'Hematologia Hfb', 'organization_id' => '1'),
                92 => array('code' => 'H2-M485', 'description' => 'Hemodinamia Hfb', 'organization_id' => '1'),
                93 => array('code' => 'H2 HDIU', 'description' => 'Hospital Diurno HFB', 'organization_id' => '1'),
                94 => array('code' => 'H2-M278', 'description' => 'Imagenologia Hfb', 'organization_id' => '1'),
                95 => array('code' => 'H2-D349', 'description' => 'Implantología Hfb', 'organization_id' => '1'),
                96 => array('code' => 'H2 20-155', 'description' => 'Infecciosos Niños HFB', 'organization_id' => '1'),
                97 => array('code' => 'H2-M434', 'description' => 'Infectologia Adulto Hfb', 'organization_id' => '1'),
                98 => array('code' => 'H2-M488', 'description' => 'Infectologia Pediatrica Hfb', 'organization_id' => '1'),
                99 => array('code' => 'H2 IEOH', 'description' => 'Interconsulta a especialidad de otro Hosp. HFB', 'organization_id' => '1'),
                100 => array('code' => 'H2 IFG', 'description' => 'Interconsulta Fundacion Ganz HFB', 'organization_id' => '1'),
                101 => array('code' => 'H2 IOSS', 'description' => 'Interconsulta otro servicio del HFB', 'organization_id' => '1'),
                102 => array('code' => 'H2 -JUR', 'description' => 'Jurídica HFB', 'organization_id' => '1'),
                103 => array('code' => 'H2 4011', 'description' => 'Kinesiologia HFB', 'organization_id' => '1'),
                104 => array('code' => 'H2 3550', 'description' => 'Kinesiología y Terapia Ocupacional', 'organization_id' => '1'),
                105 => array('code' => 'H2-M272', 'description' => 'Laboratorio Clinico HFB', 'organization_id' => '1'),
                106 => array('code' => 'H2 20-153', 'description' => 'Lactante HFB', 'organization_id' => '1'),
                107 => array('code' => 'HFB_LOCAL DE PRUEBA', 'description' => 'Local Prueba Ambulatorio', 'organization_id' => '1'),
                108 => array('code' => 'H2 3985', 'description' => 'Mantenimiento HFB', 'organization_id' => '1'),
                109 => array('code' => 'H2-M212.1.1', 'description' => 'Medicina del personal HFB', 'organization_id' => '1'),
                110 => array('code' => 'H2-M491', 'description' => 'Medicina De Urgencia Hfb', 'organization_id' => '1'),
                111 => array('code' => 'H2-M476', 'description' => 'Medicina Familiar Mención Adulto Hfb', 'organization_id' => '1'),
                112 => array('code' => 'H2-M477', 'description' => 'Medicina Familiar Mención Pediátrica Hfb', 'organization_id' => '1'),
                113 => array('code' => 'H2-M215', 'description' => 'Medicina Fisica Y Rehabilitacion Hfb', 'organization_id' => '1'),
                114 => array('code' => '10-110120-CUIPAL', 'description' => 'Medicina General - Cuidados Paliativos HFB', 'organization_id' => '1'),
                115 => array('code' => 'H2-M209', 'description' => 'Medicina General Hfb', 'organization_id' => '1'),
                116 => array('code' => 'H2-M433', 'description' => 'Medicina Intensiva Adulto Hfb', 'organization_id' => '1'),
                117 => array('code' => 'H2-M489', 'description' => 'Medicina Intensiva Pediatrica Hfb', 'organization_id' => '1'),
                118 => array('code' => 'H2-M212.1', 'description' => 'Medicina Interna - Diabetes HFB', 'organization_id' => '1'),
                119 => array('code' => 'H2-M212', 'description' => 'Medicina Interna Hfb', 'organization_id' => '1'),
                120 => array('code' => 'H2MIPREO', 'description' => 'Medicina Interna PreOperatorio HFB', 'organization_id' => '1'),
                121 => array('code' => 'H2-M212.2', 'description' => 'Medicina Interna TACO HFB', 'organization_id' => '1'),
                122 => array('code' => 'H2-M283', 'description' => 'Medicina Legal Hfb', 'organization_id' => '1'),
                123 => array('code' => 'H2-M217', 'description' => 'Medicina Nuclear Hfb', 'organization_id' => '1'),
                124 => array('code' => 'H2-M480', 'description' => 'Medicina Reproductiva E Infertilidad Hfb', 'organization_id' => '1'),
                125 => array('code' => 'H2-M785', 'description' => 'Medico Becado Primario Hfb', 'organization_id' => '1'),
                126 => array('code' => 'H2-M787', 'description' => 'Medico En Comision De Estudios (Becado De Retorno) Hfb', 'organization_id' => '1'),
                127 => array('code' => 'H2-M798', 'description' => 'Medico General Etapa Destinacion Y Formacion Hfb', 'organization_id' => '1'),
                128 => array('code' => 'H2-M800', 'description' => 'Medico Periodo Asistencial Obligatorio Hfb', 'organization_id' => '1'),
                129 => array('code' => 'H2-M493', 'description' => 'Microbiologia Hfb', 'organization_id' => '1'),
                130 => array('code' => 'H2-M429', 'description' => 'Nefrologia Adulto Hfb', 'organization_id' => '1'),
                131 => array('code' => 'H2-M445', 'description' => 'Nefrologia Pediatrico Hfb', 'organization_id' => '1'),
                132 => array('code' => 'H2-M446', 'description' => 'Neonatologia Hfb', 'organization_id' => '1'),
                133 => array('code' => 'H2-M218', 'description' => 'Neurocirugia Hfb', 'organization_id' => '1'),
                134 => array('code' => 'H2-M221', 'description' => 'Neurologia Adulto Hfb', 'organization_id' => '1'),
                135 => array('code' => 'H2-M448', 'description' => 'Neurologia Pediatrica Hfb', 'organization_id' => '1'),
                136 => array('code' => 'H2-M224', 'description' => 'Neuropsiquiatra Infantil Hfb', 'organization_id' => '1'),
                137 => array('code' => 'H2-M490', 'description' => 'Nutricion Y Diabetes Hfb', 'organization_id' => '1'),
                138 => array('code' => '10-110120-OBS', 'description' => 'Obstetricia HFB', 'organization_id' => '1'),
                139 => array('code' => 'H2-M227', 'description' => 'Obstetricia Y Ginecologia Hfb', 'organization_id' => '1'),
                140 => array('code' => 'H2-D310', 'description' => 'Odontologia Hfb', 'organization_id' => '1'),
                141 => array('code' => '10-110120-ODON', 'description' => 'Odontologia - Protesis Removible', 'organization_id' => '1'),
                142 => array('code' => '10-110120-MAXILO', 'description' => 'Odontología-Cirugía Maxilo Facial', 'organization_id' => '1'),
                143 => array('code' => '10-110120-ODONTOFUNCIONARIOS', 'description' => 'Odontología General Funcionarios', 'organization_id' => '1'),
                144 => array('code' => 'H2-D350', 'description' => 'Odontología Legal Hfb', 'organization_id' => '1'),
                145 => array('code' => 'H2-D343', 'description' => 'Odontopedriatria Hfb', 'organization_id' => '1'),
                146 => array('code' => 'H2-M230', 'description' => 'Oftalmologia Hfb', 'organization_id' => '1'),
                147 => array('code' => 'H2 4001', 'description' => 'OIRS HFB', 'organization_id' => '1'),
                148 => array('code' => 'H2-M482', 'description' => 'Oncologia Adulto Hfb', 'organization_id' => '1'),
                149 => array('code' => 'H2-M232', 'description' => 'Oncologia Medica Hfb', 'organization_id' => '1'),
                150 => array('code' => 'H2-M483', 'description' => 'Oncologia Pediatrica Hfb', 'organization_id' => '1'),
                151 => array('code' => 'H2-M487', 'description' => 'Oncologia Y Radioterapia Hfb', 'organization_id' => '1'),
                152 => array('code' => 'H2-D348', 'description' => 'Ortodoncia Hfb', 'organization_id' => '1'),
                153 => array('code' => 'H2-M233', 'description' => 'Otorrinolaringologia Hfb', 'organization_id' => '1'),
                154 => array('code' => 'H4 OTRO', 'description' => 'Otros Hfb', 'organization_id' => '1'),
                155 => array('code' => 'H2 PC', 'description' => 'PABELLON CENTRAL HFBC', 'organization_id' => '1'),
                156 => array('code' => '10-110120-PQX', 'description' => 'Pabellónes Quirurgicos HFBC', 'organization_id' => '1'),
                157 => array('code' => 'PYP', 'description' => 'Parto/PreParto HFB', 'organization_id' => '1'),
                158 => array('code' => 'H2-D365', 'description' => 'Patología Oral Hfb', 'organization_id' => '1'),
                159 => array('code' => 'H2-M236', 'description' => 'Pediatria Hfb', 'organization_id' => '1'),
                160 => array('code' => 'H2 3303', 'description' => 'Pensionado HFB', 'organization_id' => '1'),
                161 => array('code' => 'H2-D345', 'description' => 'Periodoncia Hfb', 'organization_id' => '1'),
                162 => array('code' => 'H2 POH', 'description' => 'Procedimiento en otro Hosp. (ERCP) HFB', 'organization_id' => '1'),
                163 => array('code' => '10-110120-PROCCARAD', 'description' => 'Procedimientos Cardiología Adulto', 'organization_id' => '1'),
                164 => array('code' => '10-110120-PROCENF', 'description' => 'Procedimientos Enfermeria', 'organization_id' => '1'),
                165 => array('code' => '10-110120-PROCGASTRO', 'description' => 'Procedimientos Gastroenterología', 'organization_id' => '1'),
                166 => array('code' => '10-110120-PROCURO', 'description' => 'Procedimientos Urología', 'organization_id' => '1'),
                167 => array('code' => 'H2-M242', 'description' => 'Psiquiatria Adultos hfb', 'organization_id' => '1'),
                168 => array('code' => 'H2-M281', 'description' => 'Psiquiatria Pediatrica Y De La Adolescencia Hfb', 'organization_id' => '1'),
                169 => array('code' => 'H4 PSE', 'description' => 'Psiquiatría enlace Hfb', 'organization_id' => '1'),
                170 => array('code' => 'H2-F320', 'description' => 'Quimico-farmaceutico Hfb', 'organization_id' => '1'),
                171 => array('code' => 'H2 3590', 'description' => 'Radiología HFB', 'organization_id' => '1'),
                172 => array('code' => 'H2-D366', 'description' => 'Rehabilitación Oral Hfb', 'organization_id' => '1'),
                173 => array('code' => 'H2-M432', 'description' => 'Reumatologia Hfb', 'organization_id' => '1'),
                174 => array('code' => '10-110120-SP4', 'description' => 'Sala de Parto - Piso 4', 'organization_id' => '1'),
                175 => array('code' => 'H2-M282', 'description' => 'Salud Publica Hfb', 'organization_id' => '1'),
                176 => array('code' => 'H2 20-154', 'description' => 'Segunda Infancia HFB', 'organization_id' => '1'),
                177 => array('code' => '10-110120-AROGIN8', 'description' => 'Servicio de ARO y Ginecología Piso 8 - Torre B', 'organization_id' => '1'),
                178 => array('code' => '10-110120-CIRUGÍAADULTO', 'description' => 'Servicio de Cirugía Adulto Piso 10 - Torre C', 'organization_id' => '1'),
                179 => array('code' => '10-110120-CIRUGIAINFANTIL', 'description' => 'Servicio de Cirugía Infantil Piso 7 - Torre C', 'organization_id' => '1'),
                180 => array('code' => '10-110120-CIRUGIAPISO11', 'description' => 'Servicio de Cirugía Piso 11 - Torre C', 'organization_id' => '1'),
                181 => array('code' => '10-110120- MEDICINAPISO6TB', 'description' => 'Servicio de Medicina Piso 6 - Torre B', 'organization_id' => '1'),
                182 => array('code' => '10-110120- MEDICINAPISO6TC', 'description' => 'Servicio de Medicina Piso 6 - Torre C', 'organization_id' => '1'),
                183 => array('code' => '10-110120-MEDICINAADULTOPISO7', 'description' => 'Servicio de Medicina Piso 7 - Torre B', 'organization_id' => '1'),
                184 => array('code' => '10-110120-MEDICINAINTERNA', 'description' => 'Servicio de Medicina Piso 9 - Torre B', 'organization_id' => '1'),
                185 => array('code' => '10-110120-MEDICINAPISO9', 'description' => 'Servicio de Medicina Piso 9 - Torre C', 'organization_id' => '1'),
                186 => array('code' => '10-110120-UPCNEO4', 'description' => 'Servicio de Neonatología Básico - Piso 4 - Torre B', 'organization_id' => '1'),
                187 => array('code' => '10-110120-PEDIATRIA2', 'description' => 'Servicio de Pediatría Piso 6 - Torre A', 'organization_id' => '1'),
                188 => array('code' => '10-110120-PEDIATRIA1', 'description' => 'Servicio de Pediatría Piso 7 - Torre A', 'organization_id' => '1'),
                189 => array('code' => '10-110120-PSIQUIADULTOHOMBRE', 'description' => 'Servicio de Psiquiatría Adulto Hombre Piso 9 - Torre A', 'organization_id' => '1'),
                190 => array('code' => '10-110120-PSIQUIADULTO', 'description' => 'Servicio de Psiquiatría Adulto Mujer Piso 10 -Torre A', 'organization_id' => '1'),
                191 => array('code' => '10-110120-PSIQUINFANTIL', 'description' => 'Servicio de Psiquiatría Infantil Piso 8 -Torre A', 'organization_id' => '1'),
                192 => array('code' => '10-110120-PP8', 'description' => 'Servicio de Puerperio y Puericultura Piso 8 - Torre C', 'organization_id' => '1'),
                193 => array('code' => '10-110120-TRAUMAADULTO', 'description' => 'Servicio de Traumatología Adulto Piso 10 - Torre B', 'organization_id' => '1'),
                194 => array('code' => '10-110120-MQ1', 'description' => 'Servicio Médico Quirúrgico Piso 1', 'organization_id' => '1'),
                195 => array('code' => 'H2-D474', 'description' => 'Somato-prótesis Hfb', 'organization_id' => '1'),
                196 => array('code' => 'H2 3900', 'description' => 'Subdirección Administrativa Hospital HFB', 'organization_id' => '1'),
                197 => array('code' => 'H2 3300', 'description' => 'Subdirección Médica Hospital HFB', 'organization_id' => '1'),
                198 => array('code' => '13-03-04H2', 'description' => 'Toma de Muestras HFB', 'organization_id' => '1'),
                199 => array('code' => 'H2-M385.1', 'description' => 'Torax Infantil HFB', 'organization_id' => '1'),
                200 => array('code' => 'H2-M245', 'description' => 'Traumatologia Y Ortopedia Adulto Hfb', 'organization_id' => '1'),
                201 => array('code' => 'H2-M402', 'description' => 'Traumatologia Y Ortopedia Pediatrico Hfb', 'organization_id' => '1'),
                202 => array('code' => 'H2-M402.4', 'description' => 'Traumatología Mano HFB', 'organization_id' => '1'),
                203 => array('code' => 'H2-M402.6', 'description' => 'Traumatología Pie Bot HFB', 'organization_id' => '1'),
                204 => array('code' => 'H2-M402.7', 'description' => 'Traumatología Reconstrucción HFB', 'organization_id' => '1'),
                205 => array('code' => 'H2-M402.2', 'description' => 'Traumatología Tobillo, Pie HFB', 'organization_id' => '1'),
                206 => array('code' => '10-110120-UPCNEO1', 'description' => 'UCI Neonatología - Piso 4 -Torre B', 'organization_id' => '1'),
                207 => array('code' => '10-110120-PREALTA', 'description' => 'Unidad de Cuidados al Alta', 'organization_id' => '1'),
                208 => array('code' => '10-110120-UCIADULTO', 'description' => 'Unidad de Cuidados Intensivos Adulto Piso 3 - Torre B', 'organization_id' => '1'),
                209 => array('code' => '10-110120-UPCPED1', 'description' => 'Unidad de Cuidados Intensivos Pediatría - Piso 3- Torre C', 'organization_id' => '1'),
                210 => array('code' => '10-110120-UEI', 'description' => 'Unidad de Emergencia Infantil HFBC', 'organization_id' => '1'),
                211 => array('code' => 'H2IIH', 'description' => 'Unidad de IIH', 'organization_id' => '1'),
                212 => array('code' => '10-110120-UUH', 'description' => 'Unidad de Pre-Hospitalización de Urgencia', 'organization_id' => '1'),
                213 => array('code' => '10-110120-UUHI', 'description' => 'Unidad de Pre-Hospitalización de Urgencia Infantil', 'organization_id' => '1'),
                214 => array('code' => 'H2-UP', 'description' => 'Unidad de Procedimiento HFB', 'organization_id' => '1'),
                215 => array('code' => '10-110120-UTIADULTO', 'description' => 'Unidad de Tratamiento Intensivo Adulto Piso 3 - Torre B', 'organization_id' => '1'),
                216 => array('code' => '10-110120-UPCPED2', 'description' => 'Unidad de Tratamiento Intermedio Pediatría - Piso 3- Torre B', 'organization_id' => '1'),
                217 => array('code' => '10-110120-UUA', 'description' => 'Unidad de Urgencia Adulto HFBC', 'organization_id' => '1'),
                218 => array('code' => '10-110120-UGO', 'description' => 'Unidad de Urgencia Gineco-Obstetrica HFBC', 'organization_id' => '1'),
                219 => array('code' => 'H2 1941', 'description' => 'Unidad Gestión Informática HFB', 'organization_id' => '1'),
                220 => array('code' => '10-11012-PREQX', 'description' => 'Unidad Pre-Quirurgica', 'organization_id' => '1'),
                221 => array('code' => 'H2-M248', 'description' => 'Urologia Hfb', 'organization_id' => '1'),
                222 => array('code' => 'H2-M248.3', 'description' => 'Urologia Infantil HFB', 'organization_id' => '1'),
                223 => array('code' => '10-110120-UPCNEO2', 'description' => 'UTI Neonatología 1 - Piso 4 -Torre B', 'organization_id' => '1'),
                224 => array('code' => '10-110120-UPCNEO3', 'description' => 'UTI Neonatología 2 - Piso 4 - Torre B', 'organization_id' => '1'),
            )
        );
    }
}
